FROM node:26-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY src ./src

FROM node:26-alpine AS runtime
ENV NODE_ENV=production
WORKDIR /app
USER node
COPY --from=build /app /app
CMD ["node", "src/store.js"]
